version: "3"

services:
  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concurrency
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data

  #  start mailhog
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

  subscription-service:
    build:
      context: .
      dockerfile: subscriptionService.dockerfile
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=concurrency sslmode=disable timezone=UTC connect_timeout=5"
      REDIS: "redis:6379"
    depends_on:
      - postgres
